language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install .
  - pip install coveralls
  - pip install -r requirements.txt

script:
  - coverage run --source=computor setup.py test

after_success:
  coveralls
