language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly" # currently points to 3.7-dev
install:
  - pip install .
  - pip install -r requirements.txt
script:
  - if [[ $TRAVIS_PYTHON_VERSION == "3.4" ]]; then py.test; else pytest; fi
